# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NFL-Survivor-League-Manager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NFL-Survivor-League-Manager
	pod 'Parse'
	pod 'IQKeyboardManagerSwift'
end
